backend:
  name: github
  repo: oscaar90/oscarspdev
  branch: main
  auth_type: implicit
  app_id: Ov23liLTTVL36gdw0YQO

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "Novedades"
    folder: "src/content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "pubDate", widget: "datetime" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "writeups"
    label: "Writeups"
    folder: "src/content/writeups"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "pubDate", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Proyectos"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Fecha", name: "pubDate", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "notes"
    label: "Notas"
    folder: "src/content/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Texto", name: "body", widget: "markdown" }
      - { label: "Fecha", name: "pubDate", widget: "datetime" }
